services:
  - type: web
    name: md-converter
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3100"
